### ISSUE TITLE
Search box displayed incorrectly

### ISSUE THREAD

**Issue by vbezruchkin** [intelliants/subrion-template-houses#9]
http://www.boracayblue.com/realestate/
Please recheck. It does not look good.

**Comment by glebovsky** [comment]
Well, 
this block should not appear on inner pages... because there are filters with same fields...

**Comment by vbezruchkin** [comment]
I guess this should be fixed anyway, as I might want to activate it for some custom pages where we don't have filters block for example :) I suppose it won't take much time to get it fixed. 

Thanks @glebovsky in advance.
